services:
  database:
    image: pgvector/pgvector:pg16
    container_name: database
    ports:
      - "5432:5432"
    networks:
      - db_network
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: graphs
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    restart: always

  backend:
    image: dictionary/backend:1.0
    working_dir: /app
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - db_network
    depends_on:
      - database
    environment:
      DB_USERNAME: user      
      DB_PASSWORD: password      
      DB_NAME: graphs
      DB_HOSTNAME: database
      DB_PORT: 5432
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
